---
- name: Ensure node homebrew package is installed.
  homebrew:
    name: node
    state: present

- name: Ensure nodenv homebrew package is installed.
  homebrew:
    name: nodenv
    state: present

- name: Ensure configured node versions are present.
  command: "nodenv install -s {{ item }}"
  with_items: "{{ node_versions }}"

- name: Ensure configured global npm package are present.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('latest') }}"
    global: yes
    state: present
  with_items: "{{ node_npm_global_packages }}"
